#!/usr/bin/env bash

function use_deps {
	cd "$root/source/meta/make/make" ;}
function use_coreutils {
	if [[ `uname` == 'Darwin' ]]; then
		[ -d "/usr/local/opt/coreutils/libexec/gnubin" ] || {
			echo "coreutils not found"
			return 1 
		} && PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" ;fi }
function use_node {
	use_node_bare || {
		return 1 
	} && if [ -f "$(dirname $(npm root))/package.json" ]; then
		[ -d "$(npm root)" ] || {
			#TODO: does not cover case of empty dependencies
			echo "node modules not installed"
			return 1 ;} fi ;}
function use_node_bare {
	. ~/.nvm/nvm.sh --no-use
	nvm use 10 > /dev/null
	[[ "$(node --version)" == "v10"* ]] || {
		echo "couldn't change to node v10"
		return 1 ;} }
function use_file {
	[ -f "$1" ] || {
		echo "$1 doesn't exist"
		return 1 ;} }

function find_project_root {
	_pwd="$(pwd)"
	cd "$(dirname "${0}")"
	git rev-parse --show-toplevel
	cd "$_pwd" ;} 
function find_temp_path {
	use_coreutils && tmp_path="$temp/$(date +%s)" && [ ! -e "$tmp_path" ] && {
		echo "$tmp_path"
	} || {
		echo "failed to find temp path"
		exit 1 ;} }

function fail {
	eval $@
	exit 1 ;}

use_coreutils || {
	exit 1 
} && {
	pwd="$(pwd)"
	root="$(find_project_root)"
	temp="$root/temp" ;}
function as_make {
	if [ "$#" -ne 2 ]; then
		echo "$(basename "$(dirname ${0})") <source> <out>"
		exit 1 ;fi

	_pwd="$(pwd)"
	cd "$pwd"
	source="$(readlink -m "${1%/}")"
	out="$(readlink -m "${2%/}")"
	cd "$_pwd" ;}

make_defs=$(cat << 'EOF'
function as_make {
	if [ "$#" -ne 2 ]; then
		echo "$(basename "$(dirname ${0})") <source> <out>"
		exit 1 ;fi

	_pwd="$(pwd)"
	cd "$pwd"
	source="$(readlink -m "${1%/}")"
	out="$(readlink -m "${2%/}")"
	cd "$_pwd" ;}
EOF
)

use_deps && as_make $@ || {
	echo "please compile $root/source/meta/make/make"
	exit 1
} && use_coreutils || (fail
) && { 
	_make="$(find_temp_path)"
	mkdir "$_make"
	rm "$_make/*" 2> /dev/null

	cp "$source/go" "$_make/copy"
	cp "$source/go" "$_make/_make"
	> "$_make/_make"

	cat "$source/go" | head -1 >> "$_make/_make"
	echo "$make_defs" >> "$_make/_make"
	cat "$source/go" | tail -n +2 >> "$_make/_make"

	cp "$_make/_make" "$source/go"

	"$root/make/go/go" "$source" "$out"

	cp "$_make/copy" "$source/go"
	} || fail echo "failed to make make"
