#!/usr/bin/env bash
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && use_file "$source" || (fail
) && {
	rm -r "$out/*"
	ln -s "$source/*" "$out"
	find merges -mindepth 1 -maxdepth 1 | while read file; do
		rm -r "$out/$file" 2> /dev/null
		ln -s "merges/$file" "$out" ;done
	} || fail echo "failed to make webapp"
