#!/usr/bin/env bash
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && use_file "$source" || (fail
) && {
	(cd "$source" && find . -type f) | sed s/^.// | while read file; do
		mkdir -p "${out%/}$file"
		rm "${out%/}$file"
		ln -s "${source%/}$file" "${out%/}$file"
		;done
	} || fail echo "failed to make build ui/assets"
