#!/usr/bin/env bash
use_deps || {
	echo "please compile $0"
	exit 1
} && "$root/make/ni/go" "$root/source/ni" "$root/out/ni" || {
	exit 1
} && "$root/out/ni/go" "$root/out/webapp" || {
	echo "failed to start ni"
	exit 1 ;}

