#!/usr/bin/env bash
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && use_file "$source" || (fail
) && time (
	rm -r "$out" 2> /dev/null
	mk -p "$out"

	("$pwd/build/scenes/,"
	) && ("$pwd/build/styles/,"
	) && ("$pwd/build/scripts/,"
	) && ("$pwd/build/assets/,"
	) ) || fail echo "failed to make ui"
