#!/usr/bin/env bash
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && use_file "$source" || (fail
) && time (
	rm -r "$out" 2> /dev/null

	(node "fn.js"
	) && (./build/scenes/go
	) && (./build/styles/go
	) && (./build/scripts/go
	) && (./build/assets/go
	) ) || fail echo "failed to make ui"
