#!/usr/bin/env bash
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && use_file "$source" || (fail
) && time (
	rm -r "$out" 2> /dev/null

	(node "fn.js"
	) && ("$pwd/build/scenes/go"
	) && ("$pwd/build/styles/go"
	) && ("$pwd/build/scripts/go"
	) && ("$pwd/build/assets/go"
	) ) || fail echo "failed to make ui"
