#!/usr/bin/env bash
use_deps || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && [ "$#" -eq 1 ] && {
	webroot="$(readlink -f "$1")" ;} || (fail echo "please specify one webroot"
) && node "hi.js" "$webroot" || fail echo "failed to host hi"
