#!/usr/bin/env bash

make_defs=$(cat << 'EOF'
function as_make {
	if [ "$#" -ne 2 ]; then
		echo "$(basename "$(dirname ${0})") <source> <out>"
		exit 1 ;fi

	_pwd="$(pwd)"
	cd "$pwd"
	source="$(readlink -m "${1%/}")"
	out="$(readlink -m "${2%/}")"
	cd "$_pwd" ;}
EOF
)

use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_coreutils || (fail
) && { 
	_make="$(find_temp_path)"
	mkdir "$_make"
	rm "$_make/*" 2> /dev/null

	cp "$source/go" "$_make/copy"
	cp "$source/go" "$_make/_make"
	> "$_make/_make"

	cat "$source/go" | head -1 >> "$_make/_make"
	echo "$make_defs" >> "$_make/_make"
	cat "$source/go" | tail -n +2 >> "$_make/_make"

	cp "$_make/_make" "$source/go"

	"$root/make/go/go" "$source" "$out"

	cp "$_make/copy" "$source/go"
	} || fail echo "failed to make make"
