#!/usr/bin/env bash
#TODO: declare cordova dep
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_coreutils || (fail
) && use_node || (fail
) && use_file "$source" || (fail
) && {
	if [ -d "$out" ]; then
		rm -r "$out" ;fi

	mkdir "$out"
	cd "$out"

	find "$source" -mindepth 1 -maxdepth 1 -print0 \
		| xargs -0 ln -s --target-directory=.

	cp --remove-destination "$(readlink -f config.xml)" config.xml
	echo "$(cat config.xml | grep -Ev "$(cat config.xml \
			| grep "engine\ name=\"" \
			| sed "s/^.\+name=\"\([^\"]\+\)\".\+/\1/" \
			| grep -v android \
			| sed "s/\(.\+\)/engine\ name=\"\1\"/" \
			| paste -sd "|" -
		)"
	)" > config.xml

	cordova prepare
	cordova-splash
	cordova-icon
	#maybe no need www?
	#zip -r cordova-android.zip config.xml www/ platforms/ plugins/
	} || fail echo "failed to make app/android"
