#!/usr/bin/env bash

use_deps || {
	echo "please compile $0"
	exit 1
} && {
	if [[ `uname` == 'Darwin' ]]; then
		echo checking gnu tools...
		command -v brew > /dev/null || { 
			echo please install homebrew then try again; 
			echo see https://github.com/Homebrew/install;
			exit 1;
		}
		brew install coreutils
		#brew install binutils
		#brew install diffutils
		#brew install ed --with-default-names
		#brew install findutils --with-default-names
		#brew install gawk
		#brew install gnu-indent --with-default-names
		#brew install gnu-sed --with-default-names
		#brew install gnu-tar --with-default-names
		#brew install gnu-which --with-default-names
		#brew install gnutls
		brew install grep --with-default-names
		#brew install gzip
		#brew install screen
		#brew install watch
		#brew install wdiff --with-gettext
		#brew install wget
		PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
		echo
		echo ;fi

	echo checking nvm version...
	[ -e ~/.nvm/nvm.sh ] || {
		echo please install nvm then try again;
		echo see https://github.com/creationix/nvm#installation;
		exit 1
	} && . ~/.nvm/nvm.sh --no-use
	nvm install 8 && \
	nvm alias node 8 && \
	nvm alias default 8
	nvm use 8
	echo
	echo

	echo checking npm version...
	if npm list -g npm@5.6.0; then
	    echo already using npm@5.6.0
	else
	    echo trying to update npm...
	    npm install -g npm@5.6.0 ;fi
	echo
	echo

	echo checking pnpm...
	if npm list -g pnpm; then
	    echo pnpm already installed
	else
	    echo trying install pnpm...
	    npm install -g pnpm ;fi
	echo
	echo

	echo refreshing elsewheres...
	./quick/elsewheres
	echo
	echo ;}
