#!/usr/bin/env bash
use_deps && as_make $@ || {
	echo "please compile $0"
	exit 1
} && use_node || (fail
) && use_file "$source" || (fail
) && {
	mkdir -p "$out" 2> /dev/null
	rm -rf "$out/*" 2> /dev/null
	ln -s "$source/*" "$out/"
	ln -s {./config.xml,./icon.png,./splash.png} "$out/"
	} || fail echo "failed to make cordova"
